### ISSUE TITLE
Map Page

### ISSUE THREAD

**Issue by nickejanssen** [nickejanssen/WOM#2]
Summary:
Create Map that shows all current users in the vicinity. 

We will be using MapBox: 
 - https://www.mapbox.com/
 - https://github.com/aai/mapbox-rails

Tasks: 
- [x]  Create Map page including the Model, View, Controller, and adjusting routes accordingly. 
- [x] Build the map using MapBox.js
 - [x] Convert the addresses to coordinates
 - [x] Build JSON object array to tell MapBox how to display markers
 - [x] Tell Rails how to respond
 - [x] Add library code before javascript_include_tag
 - [x] Initialize Map
 - [x] Make the AJAX call
 - [ ] Create the custom popups
 - [ ] Optional: Open Popup Programmatically from a sidebar
- [ ] Ensure UX functionality and appropriate aesthetics for page

**Comment by nickejanssen** [comment]
Found a good tutorial on setting up MapBox with Rails:

http://www.bryceholcomb.com/2015/02/10/mapbox-and-rails/

**Comment by PAMulligan** [comment]
I followed this tutorial all the way through, but it still isn't appearing on the page.
