### ISSUE TITLE
Registration Error.

### ISSUE THREAD

**Issue by nickejanssen** [nickejanssen/WOM#7]
I pushed the application to heroku for testing, but when I tried to register I received this error:

Net::SMTPFatalError (550 Unauthenticated senders not allowed):

I will continue to look into this. Let me know if anybody else has time to check this issue out.

**Comment by NumberI** [comment]
it said that server can't send email after user registration.

**Comment by NumberI** [comment]
Need to add ENV['USERNAME'], ENV['PASSWORD'] for mailer
